name: Rust

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run tests with features
        run: cargo test --verbose --features regex-match
      - name: Run benchmarks
        run: cargo bench
      - name: Run benchmarks with features
        run: cargo bench --features regex-match
      - name: Clippy (automata)
        run: cargo clippy -p automata -- -D warnings
      - name: Clippy (lexer-generator)
        run: cargo clippy -p lexer-generator -- -D warnings
      - name: Clippy (parser-generator)
        run: cargo clippy -p parser-generator -- -D warnings
      - name: Clippy (postgresql-cst-parser)
        run: cargo clippy -p postgresql-cst-parser -- -D warnings
